
services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "3308:3306"
    env_file:
      - .env.dev.local
###< doctrine/doctrine-bundle ###
  app:
    env_file:
      - .env.dev.local
    volumes:
      - .:/app
